name: Deploy NexView

on:
  push:
    branches:
      - main

concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: nexviewdigital-signage
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/nexviewdigital-signage/htdocs/signage.nexviewdigital.com
            ./deploy.sh
